spring:
  application:
    name: service-a
  profiles:
    active: "dev"
  cloud:
    consul:
      host: 127.0.0.1
      discovery:        
        instanceId: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        prefer-ip-address: true
        health-check-critical-timeout: "1m"

server:
  port : 8080

serviceb:
  url: http://service-b

servicec:
  url: http://service-c

---

spring:
  profiles: dev

server:
  port : 8081

---

spring:
  profiles: prod
  